// @ts-nocheck
// This file is automatically generated. Do not modify it manually.

// Follow the instructions in the README file to configure Firebase.
export const firebaseConfig = {
  apiKey: "AIzaSyAtVFQACqDw6fqkXvOpr90Dg-cNeAVD6EY",
  authDomain: "allergytest-spanish-7752-de593.firebaseapp.com",
  projectId: "allergytest-spanish-7752-de593",
  appId: "1:251386787609:web:bf1db0709d83532075b788",
  messagingSenderId: "251386787609"
};
